name: Test & Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Use PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: "nc_news_test"
          postgresql user: "postgres"
          postgresql password: "password"

      - name: Install dependencies
        run: npm ci

      - name: Setup test database
        run: |
          psql -U postgres -d nc_news_test -f ./db/setup.sql
        env:
          PGPASSWORD: password

      - name: Run tests
        env:
          PGDATABASE: nc_news_test
          PGUSER: postgres
          PGPASSWORD: password
        run: npm test
